### ISSUE TITLE
Keyboard doesn't appear in compose view

### ISSUE THREAD

**Issue by ghost** [Stimpy5050/Twitter-Plugin-for-LockInfo#1]
There seems to be some Keyboard appearance issue with the current repository version. Is the latest repository version exactly same as the one released in Cydia? The Cydia version however doesn't have this issue.

**Comment by Burgch** [comment]
No it isn't, the Cydia version includes a few Springboard and UIKit hooks to make the keyboard appear. I'm currently working on reverse engineering the method Apple uses to show the keyboard on the lockscreen, so I'll let you know when I have that cracked. I do have a working fix, but it is quite hacky.

Conor

**Comment by Burgch** [comment]
As a side note, you can see the hooked methods by running nm on the cydia twitter binary. They're also in the current commit of the Facebook plugin.

Conor

**Comment by Stimpy5050** [comment]
It looks like it is different.  Let me integrate the changes back in.

dave

**Comment by Stimpy5050** [comment]
I pushed an update that has the keyboard fixed.  I also externalized the consumer key and secret.  You'll need to create a file called TwitterAuthSecrets.h with yours in it.  I'll build with the proper keys when we're ready.  I can't get the data to load right now though… something odd is happening.

dave

**Comment by ghost** [comment]
Cool. Keyboard now appears but there are still some minor issues. Once appeared keyboard is not hiding reliably. May be previewWillDismiss is not getting called sometimes. May be [self.plugin dismissPreview] bypasses those callback/delegates?

When I tried adding hideKeyboard explicitly in dismissTweet it worked though.

**Comment by Burgch** [comment]
Oh yeah, you're right, there is an issue with showPreview and dismissPreview not calling the delegate methods. You can bypass it by using [[[objc_getClass("LockInfoController") sharedInstance] preview] dismiss];

**Comment by Burgch** [comment]
Oh and remember #include <objc/runtime.h> of course.

**Comment by Burgch** [comment]
Ignore that for the time being. Just call hideKeyboard with dismissPreview for now :)
